### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 1104211831** [Pactortester/swaggerjmx#2]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Pactortester** [comment]
- 看起来是json解析出错了，应该是swagger的链接传的不对，

- 请传入这样的 ur：l` http://ip:port/v2/api-docs`

例如这样：

![image](https://user-images.githubusercontent.com/29191106/87223798-7bfd1500-c3b2-11ea-9d08-c570cec0da3f.png)

**Comment by Pactortester** [comment]
如果喜欢此工具的话，可以点个star !!!

**Comment by 1104211831** [comment]
我就是这个链接







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/swaggerjmx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 晚上8:10
收件人:&nbsp;"Pactortester/swaggerjmx"<swaggerjmx@noreply.github.com&gt;;
抄送:&nbsp;"╅帝歌拭魂╄"<1104211831@QQ.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/swaggerjmx] 报错 (#2)





  
 
看起来是json解析出错了，应该是swagger的链接传的不对，
 
 
 
请传入这样的 ur：l http://ip:port/v2/api-docs
 
  
例如这样：

**Comment by Pactortester** [comment]
先点个satr!!!

你打开此链接 `http://ip:port/v2/api-docs` 是json串吗？ 请确认是否能访问这个链接！

**Comment by 1104211831** [comment]
点satr了，我打开这个链接是json字符串&nbsp; 能正常打开


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/swaggerjmx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 晚上8:23
收件人:&nbsp;"Pactortester/swaggerjmx"<swaggerjmx@noreply.github.com&gt;;
抄送:&nbsp;"╅帝歌拭魂╄"<1104211831@QQ.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/swaggerjmx] 报错 (#2)





 
先点个satr!!!
 
你打开此链接 http://ip:port/v2/api-docs 是json串吗？ 请确认是否能访问这个链接！

**Comment by Pactortester** [comment]
已修复请更新v1.0.4 验证
pip install swaggerjmx==1.0.4 -i https://pypi.org/simple
