### ISSUE TITLE
文件路径定义问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [Pactortester/swaggerjmx#5]
1）不能正确读取json文件路径
![image](https://user-images.githubusercontent.com/41558924/99767834-b172f580-2b3e-11eb-80d1-4973e6a6308e.png)

2）生成的jmx文件默认路径是什么？

**Comment by Pactortester** [comment]
你的路径写法有问题，路径转义了，需要多加一个斜杠
![image](https://user-images.githubusercontent.com/29191106/99768328-86d56c80-2b3f-11eb-95a3-421aea6233c1.png)

**Comment by LuanShiZhiJian** [comment]
> 你的路径写法有问题，路径转义了，需要多加一个斜杠
> ![image](https://user-images.githubusercontent.com/29191106/99768328-86d56c80-2b3f-11eb-95a3-421aea6233c1.png)

如下图
![image](https://user-images.githubusercontent.com/41558924/99769195-ea13ce80-2b40-11eb-82d9-d35d55af1900.png)

**Comment by Pactortester** [comment]
**### 请点个star 啊！！！**

请确保你的json文件是从swaager复制下来的，http://ip:port/v2/api-doc  从这个地方打开复制
![image](https://user-images.githubusercontent.com/29191106/99769588-81792180-2b41-11eb-8677-e1d3721ad516.png)

需要登录才能访问的，可以复制swagger_url页面上的json信息，保存json文件，使用Demo_2方式转换

**Comment by LuanShiZhiJian** [comment]
> **### 请点个star 啊！！！**
> 
> 请确保你的json文件是从swaager复制下来的，http://ip:port/v2/api-doc 从这个地方打开复制
> ![image](https://user-images.githubusercontent.com/29191106/99769588-81792180-2b41-11eb-8677-e1d3721ad516.png)
> 
> 需要登录才能访问的，可以复制swagger_url页面上的json信息，保存json文件，使用Demo_2方式转换

![image](https://user-images.githubusercontent.com/41558924/99769996-285dbd80-2b42-11eb-8c35-853dc168f77c.png)
已经start！！！json文件没有问题。
“登录”是指输入用户名或密码访问swagger的吗？如果是那么我这边没有的。

**Comment by LuanShiZhiJian** [comment]
> **### 请点个star 啊！！！**
> 
> 请确保你的json文件是从swaager复制下来的，http://ip:port/v2/api-doc 从这个地方打开复制
> ![image](https://user-images.githubusercontent.com/29191106/99769588-81792180-2b41-11eb-8677-e1d3721ad516.png)
> 
> 需要登录才能访问的，可以复制swagger_url页面上的json信息，保存json文件，使用Demo_2方式转换

使用swagger_url结果如下：
![image](https://user-images.githubusercontent.com/41558924/99770716-e1bc9300-2b42-11eb-962c-0fff10da72a5.png)

**Comment by Pactortester** [comment]
老哥 我觉得你不要再cmd执行了，你有pycharm么，在里面执行试试，不行你打我

**Comment by LuanShiZhiJian** [comment]
> 老哥 我觉得你不要再cmd执行了，你有pycharm么，在里面执行试试，不行你打我

没问题了，是开发的swagger一个例子不符合json格式，所以失败了。
现在已经调整运行成功了，然后jmx文件默认路径在哪里呢？

**Comment by Pactortester** [comment]
### **给我其他项目也点个star啊！！！**

和你脚本同一级目录的jmx文件夹下面！！！

**Comment by LuanShiZhiJian** [comment]
> ### **给我其他项目也点个star啊！！！**
> 和你脚本同一级目录的jmx文件夹下面！！！

star!star!star!
